### ISSUE TITLE
ERROR: Invalid published port: 33472/tcp

### ISSUE THREAD

**Issue by LukeDefeo** [ansrivas/spark-structured-streaming#2]
Hi i have installed docker for mac and i try to run 
```
docker-compose up -d
```

but i get 

```
ERROR: Invalid published port: 33472/tcp
```

Any ideas. Sorry im not that familiar with docker

**Comment by ansrivas** [comment]
Hi, 
This was an old docker-compose from previous version of docker. I have fixed it in the master branch, you can test it, should work.

**Comment by albertozeni** [comment]
Hi, when I run main.py I get this, any ideas?

`Traceback (most recent call last):
  File "main.py", line 32, in <module>
    pykafka_producer()
  File "main.py", line 22, in pykafka_producer
    with topic_to_write.get_producer(use_rdkafka=use_rdkafka) as producer:
  File "/Users/Alberto/anaconda3/lib/python3.6/site-packages/pykafka/topic.py", line 89, in get_producer
    raise ImportError("use_rdkafka requires rdkafka to be installed")
ImportError: use_rdkafka requires rdkafka to be installed
MacBook-Pro-di-Alberto-2:setup Alberto$ `

**Comment by ansrivas** [comment]
Hi @albertozeni , 

1. Turn this off here: 
`def pykafka_producer(use_rdkafka=False):`

https://github.com/ansrivas/spark-structured-streaming/blob/4d88e2bbab1ef5aa8872460abfa2404f5e7b2c43/setup/main.py#L16 

or

2. you can install [librdkafka](https://github.com/edenhill/librdkafka)
