### ISSUE TITLE
Closure issue

### ISSUE THREAD

**Issue by albertozeni** [ansrivas/spark-structured-streaming#4]
Hi, when running sbt clean compile run i get this warning and the execution stops, can you help me?
<img width="1280" alt="screenshot 2017-10-15 10 17 08" src="https://user-images.githubusercontent.com/22840782/31582984-330ce292-b192-11e7-8136-ab417f47197c.png">

**Comment by ansrivas** [comment]
Hi @albertozeni,

The execution is not stopped here. 

At this point you run `python main.py`, thus data is published on Kafka. 
To check your data in Cassandra finally run this:

`docker exec -it cas_01_test cqlsh -e 'select * from my_keyspace.test_table ;'`

I will see what is the reason of this warning and will try to fix it, but this won't stop you from executing the project.

**Comment by albertozeni** [comment]
Thanks so much! It works!
