### ISSUE TITLE
Spark Logs

### ISSUE THREAD

**Issue by albertozeni** [ansrivas/spark-structured-streaming#5]
Where are the Logs produced by spark?
Thanks in advance for all the support,
Alberto

**Comment by ansrivas** [comment]
Hi, 
Change the log level here to `DEBUG` or `INFO` and you will see the logs:
https://github.com/ansrivas/spark-structured-streaming/blob/4d88e2bbab1ef5aa8872460abfa2404f5e7b2c43/src/main/scala/com/kafkaToSparkToCass/Main.scala#L23

**Comment by albertozeni** [comment]
hi,
how can i save the logs into a file?
Alberto
