### ISSUE TITLE
Spark Event Logs

### ISSUE THREAD

**Issue by albertozeni** [ansrivas/spark-structured-streaming#6]
Hi, sorry for asking again, 
I need to access the event logs of spark, but i cannot find the script that starts the history server neither instructions to modify the log4.properties file, can you help me?
Thanks in advance,
Alberto

**Comment by ansrivas** [comment]
Hi @albertozeni ,
In your spark cluster code ( the source I mean ) inside `sbin` directory you can start the history server.
For more details you can see this
https://spark.apache.org/docs/latest/monitoring.html#viewing-after-the-fact

For modifying log4j refer to this article here: 
`https://docs.oracle.com/cd/E29578_01/webhelp/cas_webcrawler/src/cwcg_config_log4j_file.html`

**Comment by albertozeni** [comment]
@ansrivas I already tried, the history server starts but it doesn't collect the events coming from the test, i thought the one I supposed to run was in the folder /spark-structured-streaming

**Comment by ansrivas** [comment]
Actually no, for history server to work you need a spark-cluster configured. This is a standalone application, you need to submit it to a cluster so that you can utilize all the functionalities of a cluster.

**Comment by albertozeni** [comment]
And how ca I do it?
Sorry but i'm a noob in spark and this is for a project,
Thanks again Alberto

**Comment by ansrivas** [comment]
Hi @albertozeni , 

Unfortunately these questions are out of the scope of this project here. Please try to ask these questions on StackOverflow.
